# Site settings
title: "Pratik Aniruddh Ambani"
description: "My resume created in Jekyll"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Pratik Ambani"
resume_title:                   "Java J2EE Developer"
resume_contact_email:           "pratikaambani@gmail.com"
resume_header_contact_info:     "+9187675994999 / +918320481769"
resume_header_intro:            "<p>A creative human being who loves exploring new technologies and frameworks. An agile learner who wishes to develop programming, technical, architectural skills in all sorts of challenging situations.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_medium_url:            "https://medium.com/@pratikaambani"
  resume_stackoverflow_url:     "https://stackoverflow.com/users/7212399/pratik-ambani"
  resume_linkedin_url:          "https://www.linkedin.com/in/pratikaambani/"
  resume_github_url:            "https://github.com/pratikaambani/"
  resume_twitter_url:           "https://twitter.com/praGeek_ambani"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "insert website here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
